authors:
  tarsil:
    name: Tiago Silva
    description: Creator
    avatar: https://github.com/tarsil.png
  PeterChain:
    name: Pedro Correia
    description: Creator
    avatar: https://github.com/PeterChain.png
