---
name: Publish

on:
  push:
    branches: ['main']

jobs:
  publish:
    name: "Publish blog"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: 3.8
      - name: "Install dependencies"
        run: "scripts/install"
      - name: Install build dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install build twine
      - name: "Deploy docs"
        run: |
          curl -X POST '${{ secrets.DEPLOY_DOCS }}'